import html2canvas from 'html2canvas';
import type { Player } from '../types';

export const downloadImage = async (elementId: string, filename: string) => {
  try {
    const element = document.getElementById(elementId);
    if (!element) {
      throw new Error('Element not found');
    }

    const canvas = await html2canvas(element, {
      backgroundColor: '#0a0e27',
      logging: false,
      scale: 2,
      useCORS: true,
      allowTaint: true,
    });

    const link = document.createElement('a');
    link.href = canvas.toDataURL('image/png');
    link.download = `${filename}-${Date.now()}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  } catch (error) {
    console.error('Error downloading image:', error);
    throw error;
  }
};

export const copyToClipboard = async (elementId: string) => {
  try {
    const element = document.getElementById(elementId);
    if (!element) {
      throw new Error('Element not found');
    }

    const canvas = await html2canvas(element, {
      backgroundColor: '#0a0e27',
      logging: false,
      scale: 2,
      useCORS: true,
      allowTaint: true,
    });

    canvas.toBlob((blob) => {
      if (blob) {
        const item = new ClipboardItem({ 'image/png': blob });
        navigator.clipboard.write([item]).then(() => {
          alert('✅ Result card copied to clipboard!');
        });
      }
    });
  } catch (error) {
    console.error('Error copying to clipboard:', error);
    throw error;
  }
};

export const copyDOMElementToClipboard = async (elementId: string) => {
  try {
    const element = document.getElementById(elementId);
    if (!element) {
      throw new Error('Element not found');
    }

    // Temporarily hide Admin gear icons before screenshot
    const gears = element.querySelectorAll('span');
    const hiddenGears: HTMLElement[] = [];
    gears.forEach(g => {
      if (g.innerText.includes('⚙️')) {
        g.style.visibility = 'hidden';
        hiddenGears.push(g);
      }
    });

    const canvas = await html2canvas(element, {
      backgroundColor: '#0a0e27',
      logging: false,
      scale: 2,
      useCORS: true,
      allowTaint: true,
      imageTimeout: 5000,
      ignoreElements: (element) => {
        return element.classList.contains('admin-ignore');
      }
    });

    // Restore gears
    hiddenGears.forEach(g => {
      g.style.visibility = '';
    });

    canvas.toBlob((blob) => {
      if (blob) {
        const item = new ClipboardItem({ 'image/png': blob });
        navigator.clipboard.write([item]).then(() => {
          alert('✅ Leaderboard copied to clipboard!');
        });
      }
    });
  } catch (error) {
    console.error('Error copying leaderboard to clipboard:', error);
    alert('Failed to copy. Try again.');
  }
};

export const shareToWhatsApp = (text: string) => {
  const message = encodeURIComponent(text);
  const whatsappUrl = `https://wa.me/?text=${message}`;
  window.open(whatsappUrl, '_blank');
};

export const generateResultSummary = (
  players: Player[],
  winner: Player,
  sessionDuration?: number
) => {
  const sortedPlayers = [...players].sort((a, b) => b.wins - a.wins);
  const topThree = sortedPlayers.slice(0, 3);

  let summary = `🏆 MATCH RESULT 🏆\n\n`;
  summary += `🥇 WINNER: ${winner.name} • ${winner.wins}W-${winner.losses}L\n\n`;

  summary += `📊 LEADERBOARD:\n`;
  topThree.forEach((player, index) => {
    const medal = ['🥇', '🥈', '🥉'][index];
    const winRate = player.wins + player.losses > 0 
      ? ((player.wins / (player.wins + player.losses)) * 100).toFixed(1)
      : '0';
    summary += `${medal} #${index + 1} ${player.name} - ${player.wins}W ${player.losses}L (${winRate}%)\n`;
  });

  if (sessionDuration) {
    summary += `\n⏱️ Duration: ${Math.floor(sessionDuration / 60)}m`;
  }

  summary += `\n\n🎮 Generated by CyberTrack`;
  return summary;
};

export const calculateWinRate = (wins: number, losses: number): number => {
  if (wins + losses === 0) return 0;
  return (wins / (wins + losses)) * 100;
};

export const getRankBadge = (rank: number): string => {
  switch (rank) {
    case 1:
      return '👑';
    case 2:
      return '⭐';
    case 3:
      return '✨';
    default:
      return '•';
  }
};

export const getConsistentColor = (index: number): string => {
  const colors = [
    'from-cyan-500 to-blue-600',
    'from-purple-500 to-pink-600',
    'from-pink-500 to-red-600',
    'from-orange-500 to-yellow-600',
    'from-green-500 to-teal-600',
    'from-indigo-500 to-purple-600',
    'from-rose-500 to-pink-600',
    'from-amber-500 to-orange-600',
  ];
  return colors[index % colors.length];
};

export const getAvatarInitials = (name: string): string => {
  return name
    .split(' ')
    .map((n) => n[0])
    .join('')
    .toUpperCase()
    .slice(0, 2);
};
